### PR TITLE
CI: Mojo and Pygments Issue

### PR DESCRIPTION
**Pull request by kp992**

### CODE REVIEW

**Comment by kp992** [comment]
@mmcky mojo is now visible in the PATH. The test file runs fine. We need to fix the jb build warnings now.

**Comment by mmcky** [comment]
Thanks @kp992 just saw this.

We ended up at the same solution :-)

**Comment by mmcky** [comment]
Would you mind looking into the `jupyter-book` warnings?

If you find a solution -- please feel free to merge to main

**Comment by kp992** [comment]
@mmcky The errors come from Pygments. It's because Pygments lacks mojo Lexer. See the available list of lexers: https://pygments.org/docs/lexers/. Also, there's one open issue related to this: https://github.com/pygments/pygments/issues/2515.

**Comment by mmcky** [comment]
thanks @kp992 I think we can build with errors on this project.

**Comment by mmcky** [comment]
@kp992 if you are happy with this branch -- please go ahead and merge.Thanks.

**Review by mmcky — APPROVED** [review]

**Comment by kp992** [comment]
Thank you @mmcky. I opened up an issue to keep a track of it.

**Pull request merged**
